name: mergesort-gtest

on: [push, pull_request]
#    paths:
#    - 'mergesort/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache gtest library
      uses: actions/cache@v2
      env:
        cache-name: cache-gtest-lib
      with:
        key: $${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/usr/local/lib/libgtest.a') }}
        path: /usr/local/lib/libgtest.a
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Compile test code
      run: g++ -Wall -g -o mergesort_test mergesort.c mergesort_test.cpp -lgtest -pthread -std=c++0x
      working-directory: mergesort
    - name: Run test
      run: ./mergesort_test
      working-directory: mergesort

